version: '3.8'

services:
  web:
    image: aiude/crypto-tracker:latest
    environment:
      # Preencha a senha aqui. Lembre-se: IP da VPS!
      - DATABASE_URL=postgresql://postgres:senha_do_seu_banco@[IP_DO_BANCO]:5432/crypto
      # Copie aqui qualquer outra variável do seu arquivo .env.local
      - NEXTAUTH_SECRET=secret_do_seu_app
      - NEXTAUTH_URL=https://crypto.aiude.com.br
      - ETHERSCAN_API_KEY=sua_api_etherscan
      - WUZAPI_URL=dominio_do_seu_wuzapi
      - WUZAPI_TOKEN=sua_wuzapi_token
      - CRON_SECRET=secret_do_seu_cron
    networks:
      - network_public
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - traefik.enable=true
        - traefik.http.routers.crypto_web.rule=(Host(`seu_dominio`))
        - traefik.http.routers.crypto_web.entrypoints=websecure
        - traefik.http.routers.crypto_web.priority=1
        - traefik.http.routers.crypto_web.tls.certresolver=letsencryptresolver
        - traefik.http.routers.crypto_web.service=crypto_web
        - traefik.http.services.crypto_web.loadbalancer.server.port=3000
        - traefik.http.services.crypto_web.loadbalancer.passHostHeader=1
        
networks:
  network_public:
    name: network_public
    external: true
